### ISSUE TITLE
Setting VAlarm.triggerDate throws FormatException

### ISSUE THREAD

**Issue by liplum** [Enough-Software/enough_icalendar#12]
## Minimal reproducible example
```dart
import 'package:enough_icalendar/enough_icalendar.dart';

void main(){
  final alarm = VAlarm();
  alarm.triggerDate = DateTime.now();
}
```
Result: 
```
FormatException: duration content needs to start with P, 20231227T025525 is invalid
#0      IsoDuration.parse (package:enough_icalendar/src/types.dart:1460:7)
#1      Property._parsePropertyValue (package:enough_icalendar/src/properties.dart:201:28)
#2      new Property (package:enough_icalendar/src/properties.dart:17:11)
#3      new TriggerProperty (package:enough_icalendar/src/properties.dart:1372:40)
#4      TriggerProperty.createWithDateTime (package:enough_icalendar/src/properties.dart:1404:9)
#5      VAlarm.triggerDate= (package:enough_icalendar/src/components.dart:1776:53)
```

**Comment by robert-virkus** [comment]
Thanks a lot, this is fixed in  v0.16.0
